// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4KquvFRZxfofgPpKGh-MjAkHn9r2tU7c',
    appId: '1:965914909551:web:b81c7299f26e668714e69a',
    messagingSenderId: '965914909551',
    projectId: 'meddapp-df3bd',
    authDomain: 'meddapp-df3bd.firebaseapp.com',
    storageBucket: 'meddapp-df3bd.firebasestorage.app',
    measurementId: 'G-WWHMFWY39F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGL76YYTDjqpbaGZb_IAd88Z3ju5bQey0',
    appId: '1:965914909551:android:275159329fe9271814e69a',
    messagingSenderId: '965914909551',
    projectId: 'meddapp-df3bd',
    storageBucket: 'meddapp-df3bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcVyDSOrWu96umXzZj8ZMcJno6MaSLxHM',
    appId: '1:965914909551:ios:ca5567b5f912875e14e69a',
    messagingSenderId: '965914909551',
    projectId: 'meddapp-df3bd',
    storageBucket: 'meddapp-df3bd.firebasestorage.app',
    iosBundleId: 'com.example.meddapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcVyDSOrWu96umXzZj8ZMcJno6MaSLxHM',
    appId: '1:965914909551:ios:ca5567b5f912875e14e69a',
    messagingSenderId: '965914909551',
    projectId: 'meddapp-df3bd',
    storageBucket: 'meddapp-df3bd.firebasestorage.app',
    iosBundleId: 'com.example.meddapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4KquvFRZxfofgPpKGh-MjAkHn9r2tU7c',
    appId: '1:965914909551:web:c007d8266311856814e69a',
    messagingSenderId: '965914909551',
    projectId: 'meddapp-df3bd',
    authDomain: 'meddapp-df3bd.firebaseapp.com',
    storageBucket: 'meddapp-df3bd.firebasestorage.app',
    measurementId: 'G-33VGT8B1D4',
  );
}
